//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoiceIsolatorUploader.Properties {
    using System;
    using System.Drawing;
    using System.Resources;
    using System.Globalization;
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;
        internal Resources() {}
        public static ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("VoiceIsolatorUploader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        public static CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }
        public static Bitmap LogoVI {
            get {
                object obj = ResourceManager.GetObject("LogoVI", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
    }
}
